### ISSUE TITLE
Metadata handling in README

### ISSUE THREAD

**Issue by ottre** [hoyon/mpv-mpris#14]
I think you should note in the README that metadata handling isn't fully implemented. In particular, there's no way to get the URL of the currently playing file.

Please correct me if I'm wrong, once the TrackList interface is added you will be able to get the URL by calling TrackList.GetTracksMetadata.

This is useful info for people who want to communicate with multiple instances of mpv playing videos.

**Comment by hoyon** [comment]
The MPRIS spec only requires the `mpris:id` metadata property to be implemented, and any others are up to the implementer to choose.

The URL property was not implemented because there is no easy way to get the URI of the current file with the mpv API, so must be constructed manually. I might give this a go though.

Regarding the TrackList interface, I don't currently intend on implementing this as it would require a lot of extra work, and I'm not sure if anything actually uses it.

**Comment by g87g4jyt8** [comment]
To implement the xesam:url metadata property, you could maybe take a look at the MPRIS interface of https://github.com/gnome-mpv/gnome-mpv, which does it.

**Comment by hoyon** [comment]
This is my initial attempt at this. It might not work in all cases, so let me know if there are any paths it doesn't work for.

**Comment by timakro** [comment]
This works nicely with gpodder. Could we get a new release?
