### ISSUE TITLE
[Gnome] Media keys don't work after a while

### ISSUE THREAD

**Issue by julien-f** [hoyon/mpv-mpris#21]
First of all, thanks for your plugin!

Since I've started using it, I noticed the media keys stops working after a while in my Gnome (Fedora 29).

Not sure if it's a Gnome specific issue or something related to your plugin, maybe like missing to free a dbus lock (take this with a pinch of salt, I don't know how it works :stuck_out_tongue_closed_eyes: ).

I have not identified the exact steps exactly but I think it has to do with running multiple instances in parallel.

If you have any idea how I could gather more info for you let me know.

**Comment by hoyon** [comment]
Thanks for using the plugin!

It very well may be due to multiple instances not playing well together. I've found that the handling of multiple players can be a bit flakey depending on the client. 

As far as I can tell, I've followed the spec when it comes to dealing with multiple instances. The spec is available [here](https://specifications.freedesktop.org/mpris-spec/latest/).

Can you try debugging the issue using [d-feet](https://wiki.gnome.org/Apps/DFeet) to find out if it is due to my plugin being unresponsive, or if gnome is not sending the correct command to the correct dbus bus.

I'm not too familiar with mpris integration in gnome so I can't really help you there - I use a custom mpris client I wrote in python.

**Comment by julien-f** [comment]
After some research, that may be due to Gnome (https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/45), I'll keep you posted when I have new info :)

**Comment by julien-f** [comment]
Killing `gsd-media-keys` (which is automatically restarted) fix the issue, so it indeed appears to be a Gnome bug.

**Comment by hoyon** [comment]
Thanks that's good to know. I'll close this for now then since it's not this plugin's bug.
