### ISSUE TITLE
Shell script as a "remote"

### ISSUE THREAD

**Issue by elundmark** [hoyon/mpv-mpris#27]
I've been using this with a script I wrote that works as my remote for controlling playback of all my open mpv windows. please check it out and do with it as you please :-)

```
Usage: $ mpv_remote COMMAND [all | PID[,PID]]
Example:  mpv_remote play all
          mpv_remote next
          mpv_remote pause 845
          mpv_remote pause 845,846

```

[mpv_remote.sh](https://gist.github.com/elundmark/a7e491a1a3b26834972adeeb4962a955)

**Comment by hoyon** [comment]
Looks great! Glad you've found this plugin useful. 

FWIW if you're only interested in controlling mpv it might be useful to look into https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst as you can do more mpv specific stuff not exposed by the mpris api.

I'm going to close this for now since it isn't really an issue.
